code: edited the automation script and ci script

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -51,35 +51,6 @@ jobs:
           docker push ${{ vars.DOCKER_HUB_USERNAME }}/py_system_monitoring_app:${{ github.sha }}
           docker push ${{ vars.DOCKER_HUB_USERNAME }}/py_system_monitoring_app:latest
 
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: ["build"]
-  #   steps:
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@v4
-
-  #     - name: Install SSH Client
-  #       run: sudo apt-get update && sudo apt-get install -y openssh-client
-
-  #     - name: Install Ansible
-  #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y ansible
-  #         ansible-galaxy collection install community.docker
-
-  #     - name: Deploy with Ansible
-  #       env:
-  #         ANSIBLE_HOST_KEY_CHECKING: "False"
-  #         DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
-  #         IMAGE_TAG: "latest"
-  #       run: |
-  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
-  #         chmod 600 private_key.pem
-  #         ansible-playbook -i ansible/hosts ansible/swarm-setup.yml \
-  #           --user ubuntu \
-  #           --private-key private_key.pem \
-  #           --extra-vars "image=${DOCKER_HUB_USERNAME}/py_system_monitoring_app:${IMAGE_TAG}"
-
   update-deployment:
     runs-on: ubuntu-latest
     needs: ["build"]
@@ -105,8 +76,17 @@ jobs:
             # Update the system
             sudo apt-get update && sudo apt-get upgrade -y
 
-            # Update your Docker Swarm service
-            sudo docker service update sw_app
+            # Pull the latest image from Docker Hub
+            sudo docker pull devpiush/py_system_monitoring_app:latest
+            # Check if the image was pulled successfully
+            if [ $? -ne 0 ]; then
+              echo "Failed to pull the latest image"
+              exit 1
+            fi
 
+            # Update your Docker Swarm service
+            sudo docker service update --image devpiush/py_system_monitoring_app:latest sw_app
+
+            rm -f id_rsa
             exit
           EOF
